---
abstract: 'A framework for high performance message passing'
author:
  - ', 2013 Dana M. Diederich. All Rights Reserved.'
  - 'Dana M. Diederich <diederich@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Transit
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  Getopt::Std: 0
  HTTP::Lite: 0
  HTTP::Server::Simple::CGI: 0
  IPC::Msg: 0
  IPC::SysV: 0
  JSON: 0
  POSIX: 0
  Storable: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/dana/perl-IPC-Transit/issues
  homepage: https://metacpan.org/module/IPC::Transit
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/dana/perl-IPC-Transit.git
version: 0.74
