---
abstract: 'A framework for high performance message passing'
author:
  - 'Dana M. Diederich <diederich@gmail.com>'
build_requires:
  IPC::SysV: 0
  IPC::Msg: 0
  POSIX: 0
  Data::Dumper: 0
  Data::Serializer: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Transit
provides:
  IPC::Transit:
    file: lib/IPC/Transit.pm
    version: 0.2
requires:
  IPC::SysV: 0
  IPC::Msg: 0
  POSIX: 0
  Data::Dumper: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.2
